from . import loc_x
from . import loc_xy
from . import loc_y
from . import loc_z
from . import res
from . import rot_x
from . import rot_y
from . import rot_z
from . import scale
from . import wp_border
from . import wp_circle_btn
from . import wp_edit_label
from . import wp_set_label
from . import wp_sketch